### ISSUE TITLE
S3 sync gives stack trace but with success

### ISSUE THREAD

**Issue by chb0github** [JustinPihony/gradle-aws-plugin-reboot#1]
```kotlin
import jp.classmethod.aws.reboot.gradle.s3.SyncTask

plugins {
    id("jp.classmethod.aws.reboot.s3") version "0.42"
}

tasks {

    register<SyncTask>("uploadCfts"){
        source = file("${projectDir}/infra/cfts")
        bucketName = "build-artifacts-us-east-1"
        prefix = project.name

    }
}
```
```bash
$ ls $PWD/build.gradle.kts
/Users/cbongiorno/dev/nexus/build.gradle.kts

$ ls $PWD/infra/cfts
00-nexus.cft            01-nexus-infra.cft      02-nexus-codedeploy.cft 03-nexus-policies.cft   04-nexus-sg.cft         05-nexus-ec2.cft        06-nexus-network.cft    07-ssl-cert.cft

```

```
Exception in thread "pool-3-thread-6" com.amazonaws.services.s3.model.AmazonS3Exception: The provided token is malformed or otherwise invalid. (Service: Amazon S3; Status Code: 400; Error Code: InvalidToken; Request ID: EC661917404D5E37; S3 Extended Request ID: bNS7SgKv9RA+g6r5Q34F72MxUy6oq0DcOf/mXvvPREReJRCB/VoUJC0lg22QtYojvYXzOmVewSE=), S3 Extended Request ID: bNS7SgKv9RA+g6r5Q34F72MxUy6oq0DcOf/mXvvPREReJRCB/VoUJC0lg22QtYojvYXzOmVewSE=

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)

        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
BUILD SUCCESSFUL in 3s
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
1 actionable task: 1 executed
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4914)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4860)
        at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:389)
        at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:5793)
        at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1786)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1746)
        at jp.classmethod.aws.reboot.gradle.s3.SyncTask$UploadTask.run(SyncTask.java:216)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
````

**Comment by JustinPihony** [comment]
I am open to a PR if you would like to fix yourself :)
